version: "3.9"

services:

  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    depends_on:
      phpfpm:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - "${HOST_WEB_PORT}:80"
    volumes:
      - ${HOME}/${DIRHOME}/src:/var/www/app
      - ./settings/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    networks:
      - api_network

  mysql:
    image: mysql:8.0.41
    container_name: ${APP_NAME}_mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${HOST_DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ${HOME}/${DIRHOME}/backups:/backups
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api_network

  phpfpm:
    build:
      context: ./settings/php
    container_name: ${APP_NAME}_phpfpm
    depends_on:
      - mysql
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE}    # off | debug | develop
      XDEBUG_CLIENT_HOST: host.docker.internal
    volumes:
      - ${HOME}/${DIRHOME}/src:/var/www/app
      - ./settings/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./settings/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./logs/php:/var/log/php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - api_network
      - smtp-bridge-network

networks:
  api_network:
    name: ${APP_NAME}_network
    external: true

  smtp-bridge-network:
    external: true

volumes:
  mysql_data:
